```{r}
setwd("evaluating_coregulation")
source("../downstreamer_functions.r")
source("data/source_olivier.r")
library(ggsignif)

datasets       <- read.downstreamer.batch(main.downstreamer.output.path, USE.CACHE = F, potential_traits = "GenePrioritization")
datasets       <- read.downstreamer.batch("data/no_celline_gene_network_test_results/", USE.CACHE = F, potential_traits = "GenePrioritization200")

# Genepvalues
files <- list.files(main.downstreamer.output.path, pattern="*_genePvalues_.*.xlsx", full.names = T)
genep <- read.genep.excel(files)
genep[is.na(genep)] <- 1

# Eqts files
eqts <-  fread(eqts.file, data.table = F)
unique.eqts.genes <- unique(eqts$Gene)

# Frequency of PGS hits per gwas
freqs <- as.data.frame(table(eqts$PGS))
freqs <- freqs[order(freqs$Freq, decreasing=T),]
```

# Overall increase of coregulation Z-score among eQTS genes
```{r}
zscores <- make.zscore.matrix(datasets)
zscores <- apply(zscores, 1, max)

is.de.gene <- names(zscores) %in% unique.eqts.genes

df.plot <- data.frame(y=zscores, x=is.de.gene)
df.plot <- na.omit(df.plot)

p <- ggplot(data=df.plot, mapping=aes(y=y, x=x)) +
  geom_hline(yintercept = median(zscores[!is.de.gene]), lty=2, col="grey") +
  geom_violin() +
  geom_boxplot(width=0.05, color="black") +
  geom_signif(comparisons = list(c("TRUE", "FALSE")), tip_length = 0) + 
  xlab("Is eQTS") +
  ylab("Max core gene score")

pdf(width=4, height=4, file="output/plots/all_eqts_vs_max_coregulation_zscore.pdf")
theme.nature(p)
dev.off()
```

# Specific examples of eQTS genes
```{r}
zscores <- make.zscore.matrix(datasets, trait="GenePrioritization200")

#pmids        <- gsub(".*_\\d{4}_(\\d+)", "\\1", colnames(zscores))
#names(pmids) <- colnames(zscores)
#eqts.link     <- unique(data.frame(id=eqts$PubmedID, name=eqts$PGS)) 
#eqts.link     <- eqts.link[eqts.link$id %in% pmids,]

eqts.plot <- function(pgs, trait) {
  subset <- eqts[ eqts$PGS == pgs,]
  is.de.gene <- rownames(zscores) %in% unique(subset$Gene)
  df.plot <- data.frame(y=zscores[,trait], x=is.de.gene)

  tmp.tab <- table(is.de.gene)
  a <- paste0("eQTS\nN=", tmp.tab["TRUE"])
  b <- paste0("Non eQTS \nN=", tmp.tab["FALSE"])
  
  df.plot[df.plot$x==T,]$x <- a
  df.plot[df.plot$x==F,]$x <- b
  df.plot$x <- factor(df.plot$x, levels=c(b,a))
  df.plot <- na.omit(df.plot)
  
  p <- ggplot(data=df.plot, mapping=aes(y=y, x=x)) +
    geom_hline(yintercept = median(zscores[!is.de.gene]), lty=2, col="grey") +
    geom_violin() +
    geom_boxplot(width=0.05, color="black") +
    xlab("Is eQTS gene") +
    geom_signif(comparisons = list(c(a, b)), tip_length = 0) + 
    ylab(paste0( trait))
  
  theme.nature(p)
}

pairs <- matrix(ncol=2)
pairs <- rbind(pairs, c("Celiac_disease_2011_22057235_hg19.txt.gz", "coeliac_disease_2011_22057235"))
pairs <- rbind(pairs, c("Inflammatory_Bowel_Disease_EUR_2015_26192919_hg19.txt.gz", "inflammatory_bowel_disease_2017_29906448"))
pairs <- rbind(pairs, c("Systemic_lupus_erythematosus_2015_26502338_hg19.txt.gz", "systemic_lupus_erythematosus_2017_28714469"))
pairs <- rbind(pairs, c("Educational_attainment_2016_27225129_hg19.txt.gz", "educational_attainment_2018_30038396"))
pairs <- rbind(pairs, c("Height_2014_25282103_rs.txt.gz", "height_2018_30124842"))
pairs <- rbind(pairs, c("Extreme_height_2013_23563607_rs.txt.gz", "height_2018_30124842"))
pairs <- rbind(pairs, c("Body_mass_index_EUR_2015_25673413_rs.txt.gz", "body_mass_index_2018_30124842"))
pairs <- rbind(pairs, c("Rheumatoid_Arthritis_2014_24390342_hg19.txt.gz", "rheumatoid_arthritis_2014_24390342"))
pairs <- rbind(pairs, c("Multiple_sclerosis_2013_24076602_hg19.txt.gz", "multiple_sclerosis_2013_24076602"))
pairs <- rbind(pairs, c("Coronary_artery_disease_additive_2015_26343387_hg19.txt.gz", "coronary_artery_disease_2018_29212778"))
pairs <- rbind(pairs, c("Major_depression_2016_27479909_hg19.txt.gz", "major_depressive_disorder_2018_29700475"))
pairs <- rbind(pairs, c("Asthma_2010_860503_random_effects_hg18_hg19.txt.gz", "asthma_2020_32296059"))
pairs <- na.omit(pairs)

plots <- apply(pairs, 1, function(pair){
  cat(pair, "\n")
  return(eqts.plot(pair[1], pair[2]))
})


pdf(width=13, height=12, file="output/plots/eqts_vs_coregulation_per_trait.pdf")
grid.arrange(grobs=plots, ncol=4)
dev.off()

#grep("Inflamm", unique(eqts$PGS), value=T)
```


```{r}
raw.eqts <- fread(raw.eqts.file, data.table = F)

pair <- pairs[1,]

prep.eqts.scatterplot <- function(pair) {
  cur.eqts        <- raw.eqts[grep(pair[1], raw.eqts$V2),]
  unique.genes    <- unique(cur.eqts$V4)
  max.eqts.zscore <- sapply(unique.genes, function(gene) {
    return(max(abs(cur.eqts[cur.eqts$V4==gene, 3])))
  })
  
  ol      <- intersect(rownames(zscores), names(max.eqts.zscore))
  df.plot <- data.frame(zscores=zscores[ol, pair[2]], eqts=max.eqts.zscore[ol])
  return(df.plot)
}

make.eqts.scatterplot <- function(pair, df.plot=NULL) {
  
  if (is.null(df.plot)) {
    df.plot <- prep.eqts.scatterplot(pair)
  }

  p <- ggplot(data=df.plot, mapping=aes(x=eqts, y=zscores)) + 
    geom_hex(bins=50, col=NA) + 
    geom_smooth(method="lm", col="#383838") +
    geom_hline(yintercept=0, col="grey", lty=2) +
    xlab("Max abs(eQTS Z-score)") + 
    ylab(pair[2]) +
    scale_fill_gradientn(colors=c("#2c6c70", "#0ae4f2")) +
    ggtitle(paste0("R: ",
                   format(cor(df.plot$zscores, df.plot$eqts, use="complete.obs"), digits=2),
                   " p-value: ",
                   format(cor.test(df.plot$zscores, df.plot$eqts, na.action=na.omit())$p.value, digits=2, scientific=T)))
  
  return(theme.nature(p))
}

df.plot <- prep.eqts.scatterplot(pairs[1,])
make.eqts.scatterplot(pairs[1,], df.plot=df.plot)


df.plot <- prep.eqts.scatterplot(pairs[2,])
make.eqts.scatterplot(pairs[2,], df.plot=df.plot)
```


