```{r}
if (basename(getwd()) == "downstreamer_main") {setwd("evaluating_coregulation")} else {setwd("../evaluating_coregulation")}
source("../downstreamer_functions.r")
source("data/source_olivier.r")

library(ggsignif)
library(ggbeeswarm)

# Read reference datasets
ensembl <- read.table(ensembl.file, sep="\t", header=T, row.names = 1, stringsAsFactors = F)
ensembl$gene.length = ensembl$Gene.end..bp. - ensembl$Gene.start..bp.
rownames(ensembl) <- make.names(ensembl$Gene.name, unique=T)

# Gnomad Pli
gnomad <- read.table(gnomad.file, sep="\t", header=T, stringsAsFactors = F)
gnomad <- gnomad[!duplicated(gnomad$gene),]
rownames(gnomad) <- make.names(gsub("\\.\\d+", "", ensembl[gnomad$gene, ]$Gene.stable.ID.version), unique=T)

# HPO genes (florannes matrix)
hpo.genes           <- fread(hpo.file, stringsAsFactors = F, sep="\t", data.table=F)
rownames(hpo.genes) <- hpo.genes[,1]
hpo.genes           <- hpo.genes[,-1]
hpo.genes           <- hpo.genes[rowSums(hpo.genes) > 1, ]
hpo.genes           <- rownames(hpo.genes)
#hpo.genes <- gsub("\\.\\d+", "", ensembl[unique(hpo.genes$V2), "Gene.stable.ID.version"])

# Cached 2021-04-16
datasets            <- read.downstreamer.batch(main.downstreamer.output.path, USE.CACHE = T)

# Gene pvalues
gene.pvalues        <- read.genep(list.files("../data/final_paper/gene_pvalues/", full.names=T), trim.colnames = c("_hg19_normalizedGenePvalues.txt", "_hg19.txt"))
ol                  <- intersect(names(datasets), colnames(gene.pvalues))

# Genepvalues
#files <- list.files(main.downstreamer.output.path, pattern="*_genePvalues_.*.xlsx", full.names = T)
#genep <- read.genep.excel(files)
#genep[is.na(genep)] <- 1

key.gene.stats <- as.data.frame(read_excel("data/GenePrioritization_key_gene_stats.xlsx", sheet = "only_key_genes"))
rownames(key.gene.stats) <- key.gene.stats$`key-gene`
```

# Max zscore vs gnomad Zscores / PLI
```{r}
zscores <- make.zscore.matrix(datasets)
ol      <- intersect(rownames(gnomad), rownames(zscores))
zscores <- apply(zscores[ol,], 1, max)

tmp <- gnomad[ol,c("syn_z", "mis_z", "lof_z", "pLI")]
tmp$max_ds_zscore <- zscores[ol]
write.table(tmp, "output/max_coregulation_zscore_and_gnomad_metrics.tsv", sep="\t", quote=F)

gnomad$max_lof_z_mis_z <- sapply(1:nrow(gnomad), function(x){max(gnomad[x, "mis_z"], gnomad[x, "lof_z"])})

make.gnomad.scatterplot <- function(trait) {
  df.plot <- data.frame(zscores=zscores[ol], gnomad=gnomad[ol, trait])

  p <- ggplot(data=df.plot, mapping=aes(x=zscores, y=gnomad)) + 
    geom_hex(bins=50, col=NA) + 
    geom_smooth(method="lm", col="grey", size=0.75) +
    geom_hline(yintercept=0, col="grey", lty=2) +
    xlab("Max key-gene score") +
    scale_fill_gradientn(colors=c("#376B65","#0ae4f2")) + #"#2c6c70", "#0ae4f2"
    ggtitle(paste0("R: ",
                   format(cor(zscores[ol], gnomad[ol, trait], use="complete.obs"), digits=2),
                   " p-value: ",
                   format(cor.test(zscores[ol], gnomad[ol, trait], na.action=na.omit())$p.value, digits=2, scientific=T)))
  
  theme.nature(p, base_size=8)
}

p1 <- make.gnomad.scatterplot("syn_z") + ylab("Gnomad Syn Z-score") + theme(legend.position = "none")
p2 <- make.gnomad.scatterplot("mis_z") + ylab("Gnomad MiS Z-score") + theme(legend.position = "none")
p3 <- make.gnomad.scatterplot("lof_z") + ylab("Gnomad LoF Z-score") + theme(legend.position = "none")
#p4 <- make.gnomad.scatterplot("max_lof_z_mis_z") + ylab("Max Gnomad LoF Mis Z-score")
pdf(width=6, height=2, file="output/plots/gnomad_zscore_vs_max_zscore.pdf", paper="a4")

grid.arrange(grobs=list(p1, p2, p3), ncol=3)

dev.off()
```

# Max Genep vs gnomad Zscores / PLI
```{r}
ol        <- intersect(rownames(gnomad), rownames(gene.pvalues))
max.genep <- apply(gene.pvalues[ol,], 1, max)

tmp               <- gnomad[ol,c("syn_z", "mis_z", "lof_z", "pLI")]
tmp$max_ds_zscore <- max.genep[ol]
#write.table(tmp, "output/max_coregulation_zscore_and_gnomad_metrics.tsv", sep="\t", quote=F)

gnomad$max_lof_z_mis_z <- sapply(1:nrow(gnomad), function(x){max(gnomad[x, "mis_z"], gnomad[x, "lof_z"])})

make.gnomad.scatterplot <- function(trait) {
  df.plot <- data.frame(max.genep=max.genep[ol], gnomad=gnomad[ol, trait])

  p <- ggplot(data=df.plot, mapping=aes(x=max.genep, y=gnomad)) + 
    geom_hex(bins=50, col=NA) + 
    geom_smooth(method="lm", col="grey", size=0.75) +
    geom_hline(yintercept=0, col="grey", lty=2) +
    xlab("Max gene p-value") +
    scale_fill_gradientn(colors=c("#376B65","#0ae4f2")) + #"#2c6c70", "#0ae4f2"
    ggtitle(paste0("R: ",
                   format(cor(max.genep[ol], gnomad[ol, trait], use="complete.obs"), digits=2),
                   " p-value: ",
                   format(cor.test(max.genep[ol], gnomad[ol, trait], na.action=na.omit())$p.value, digits=2, scientific=T)))
  
  theme.nature(p, base_size=8)
}

p1 <- make.gnomad.scatterplot("syn_z") + ylab("Gnomad Syn Z-score") + theme(legend.position = "none")
p2 <- make.gnomad.scatterplot("mis_z") + ylab("Gnomad MiS Z-score") + theme(legend.position = "none")
p3 <- make.gnomad.scatterplot("lof_z") + ylab("Gnomad LoF Z-score") + theme(legend.position = "none")
pdf(width=6, height=2, file="output/plots/gnomad_zscore_vs_max_genep.pdf", paper="a4")

grid.arrange(grobs=list(p1, p2, p3), ncol=3)

dev.off()
```

# Number of classes vs gnomad
```{r}
ol      <- intersect(rownames(gnomad), rownames(key.gene.stats))

df.plot                  <- data.frame(lof.z=gnomad[, "lof_z"], row.names=rownames(gnomad))
df.plot$class.count      <- key.gene.stats[rownames(df.plot), ]$class.count
#df.plot[is.na(df.plot$class.count), "class.count"] <- 0
df.plot <- na.omit(df.plot)
df.plot$class     <- as.factor(df.plot$class.count)

ct <- cor.test(df.plot$lof.z, df.plot$class.count)

p1 <- ggplot(data=df.plot, mapping=aes(x=class, y=lof.z)) +
  geom_hline(yintercept = 0, lty=2, col="#c2c2c2") +
  geom_violin(alpha=0.4) +
  geom_quasirandom(color = "#376B65", alpha=0.4) +
  geom_boxplot(width=0.2, outlier.color = "#376B65", alpha=0.4) +
  geom_smooth(mapping=aes(x=class.count), method="lm", col="#c2c2c2", alpha=0.2, size=0.75) +
  ylab("Gnomad LoF Z-score") +
  xlab("Number of classes key-gene is significant in") +
  scale_x_discrete(limits=c(1:10)) +
  ggtitle(paste0("Pearson R: ", format(ct$estimate, digits=2),
              " p-value: ", format(ct$p.value, digits=2, scientific=T)))
  #geom_signif(comparisons = list(c(1, 9)), tip_length = 0)


pdf(width=5, height=2.5,file="output/plots/GenePrioritization_classes_of_keygenes_vs_constraint.pdf", paper="a4")
theme.nature(p1)
dev.off()



x <- sapply(1:9, function(x){median(df.plot[df.plot$class.count ==x, 1])})
cor(1:9, x)

plot(1:9, x)

```













# HPO genes and Pli
```{r}
hpo.genes             <- intersect(hpo.genes, rownames(gnomad))
bonf.sig.gwas.genes   <- rownames(genep)[rowSums(genep < (0.05 / (nrow(genep) * ncol(genep)))) >=1]

bonf.sig.coreg.genes  <- unique(unlist(lapply(datasets, function(dataset){
  coreg <- dataset$Coregulation
  coreg <- coreg[coreg$Enrichment.Z.score > 0,]
  return(coreg$Gene.set[coreg$Bonferroni.significant])
})))

others                <- rownames(gnomad)[!rownames(gnomad) %in% unique(c(hpo.genes, bonf.sig.coreg.genes))]


make.gnomad.violin.plot      <- function(trait) {
  df.plot <- data.frame(pli=c(gnomad[others,trait],
                            gnomad[bonf.sig.coreg.genes,trait],
                            gnomad[bonf.sig.gwas.genes, trait],
                            gnomad[hpo.genes, trait]),
                      annot=factor(c(rep(paste0("Not core|HPO gene N=", length(others)), length(others)), 
                              rep(paste0("Core genes N=", length(bonf.sig.coreg.genes)), length(bonf.sig.coreg.genes)),
                              rep(paste0("GWAS genes N=", length(bonf.sig.gwas.genes)), length(bonf.sig.gwas.genes)),
                              rep(paste0("HPO genes N=", length(hpo.genes)), length(hpo.genes))),
                              levels=c(paste0("Core genes N=", length(bonf.sig.coreg.genes)),
                                       paste0("HPO genes N=", length(hpo.genes)),
                                       paste0("GWAS genes N=", length(bonf.sig.gwas.genes)),
                                       rep(paste0("Not core|HPO gene N=", length(others))))))


  p <- ggplot(df.plot, aes(y=pli, x=annot, fill=annot)) +
  geom_violin(color="white", scale="width") +
    geom_boxplot(width=0.05, color="black") +
    xlab("") +
      geom_signif(comparisons=list(c(paste0("Core genes N=", length(bonf.sig.coreg.genes)),
                                 paste0("GWAS genes N=", length(bonf.sig.gwas.genes))),
                               c(paste0("Core genes N=", length(bonf.sig.coreg.genes)),
                                 paste0("Not core|HPO gene N=", length(others))),
                               c(paste0("Core genes N=", length(bonf.sig.coreg.genes)),
                                 paste0("HPO genes N=", length(hpo.genes)))),
              tip_length = 0, step_increase=0.1)
  p <- theme.nature(p) + scale_fill_manual(values=c("dodgerblue3", "#3BB273", "goldenrod2", "#8576B6")) + theme(legend.position = "none")


return(p)
}

gnomad$max_lof_z_mis_z <- sapply(1:nrow(gnomad), function(x){max(gnomad[x, "mis_z"], gnomad[x, "lof_z"])})

pdf(width=8, height=3, file= "output/plots/pli_comparrison_all.pdf")
make.violin.plot("pLI") + ylab("Gnomad pLI score")
dev.off()

p1 <- make.gnomad.violin.plot("syn_z") + ylab("Gnomad Syn Z-score") + geom_hline(yintercept=0, col="grey", lty=2) 
p2 <- make.gnomad.violin.plot("mis_z") + ylab("Gnomad Mis Z-score") + geom_hline(yintercept=0, col="grey", lty=2) 
p3 <- make.gnomad.violin.plot("lof_z") + ylab("Gnomad LoF Z-score") + geom_hline(yintercept=0, col="grey", lty=2)
p4 <- make.gnomad.violin.plot("max_lof_z_mis_z") +
  ylab("Max Gnomad LoF Mis Z-score") +
  geom_hline(yintercept=0, col="grey", lty=2)

pdf(width=16, height=5, file= "output/plots/gnomad_zscore_comparrison_all.pdf")
grid.arrange(grobs=list(p1, p2, p3), ncol=3)
dev.off()
```

