```{r}
setwd("evaluating_coregulation")
source("../downstreamer_functions.r")
source("data/source_olivier.r")

library(ggsignif)

datasets <- read.downstreamer.batch(main.downstreamer.output.path, USE.CACHE = T)

ced.prio <- as.data.frame(read_excel(aadriaan.ced.prio,
                       col_types = c(rep("text", 4), rep("numeric", 3), "text", "numeric", "text", "text"), na=c("NA")))

rownames(ced.prio) <- ced.prio$ensembl_id
ced.prio$lines_of_evidence_v2  <- gsub("(\\d)\\/\\d", "\\1", ced.prio$lines_of_evidence)
ced.prio$ld_overlap_summary_v2 <- T
ced.prio[ced.prio$ld_overlap_summary %in% c("No LD", "No eQTL"), ]$ld_overlap_summary_v2 <- F
```


```{r}
cur.dataset <- datasets$coeliac_disease_2011_22057235$Coregulation
ol          <- intersect(ced.prio$ensembl_id, cur.dataset$Ensembl.Gene.ID)


violin.plot <- function(other.trait, xlab="", comps=list(), ylim=NULL) {
    df.plot <- data.frame(x=other.trait, y=cur.dataset[ol,]$Enrichment.Z.score)
    df.plot <- na.omit(df.plot)
    
    p <- ggplot(data=df.plot, mapping=aes(y=y, x=x)) +
    geom_hline(yintercept = 0, lty=2, col="grey") +
    geom_hline(yintercept = -4.71, lty=2, col="grey") +
    geom_hline(yintercept = 4.71, lty=2, col="grey") +
    geom_violin() +
    geom_boxplot(width=0.05, color="black") +
    geom_signif(comparisons = comps, tip_length = 0) + 
    xlab(xlab) +
    ylab("Enrichment Z-score")
    
    if (!is.null(ylim)) {
      p <- p + ylim(ylim)
    }
    
    return(theme.nature(p))
}

p1 <- violin.plot(ced.prio[ol,]$depict_fdr_pass, "Depict FDR pass", comps=list(c("No", "Yes")))
p2 <- violin.plot(ced.prio[ol,]$MR_ivw_p_value < 0.05, "MR ivw < 0.05", comps=list(c("FALSE", "TRUE")))
p3 <- violin.plot(ced.prio[ol,]$coloc_h4 > 0.9, "Coloc H4 > 0.9", comps=list(c("FALSE", "TRUE")))
p4 <- violin.plot(ced.prio[ol,]$ld_overlap_summary_v2,"Shared eQTL" , comps=list(c("FALSE", "TRUE")))

pdf(width=14, height=3.5, file="output/plots/ced_gene_prio_vs_coregulation.pdf")
grid.arrange(grobs=list(p4, p1, p2, p3), ncol=4)
dev.off()
```


