```{r}
setwd("evaluating_coregulation")
source("../downstreamer_functions.r")
source("data/source_olivier.r")

files <- list.files("~/Desktop/depict2/collaborations/harm_jan/", pattern="*.xlsx", full.names=T)
datasets <- list()
for (file in files) {
  name <- gsub("\\_hg19\\_enrichtments\\_exHla\\.xlsx", "", basename(file))
  name <- gsub("\\_hg19\\_enrichtments\\_exHla\\_1\\.xlsx", "", name)
  name <- gsub("\\_enrichtments\\_exHla\\.xlsx", "", name)
  name <- gsub("\\_hg19\\.txt\\_exHla\\.xlsx", "", name)

  datasets[[name]] <- read.depict2(file)
}
```


```{r}
make.plot <- function(trait) {

  curdata.x <- curset[[paste0(trait)]]
  curdata.y <- curset[[paste0(trait, "_Cortex")]]
  ol        <- intersect(rownames(curdata.x), rownames(curdata.y))
  curdata.x <- curdata.x[ol,]
  curdata.y <- curdata.y[ol,]
  
  p <- xy.plot.pvalue.colored(curdata.x$Enrichment.Z.score, curdata.x$Enrichment.P.value, curdata.y$Enrichment.Z.score, curdata.y$Enrichment.P.value, xlab=paste0(trait), ylab=paste0(trait, "_Cortex"))
  
  return(p)
}


curset <- datasets[["multiple_sclerosis_patsopoulos_harm_jan_enrichtments_exHla_coregulation_only.xlsx"]]
p1 <- make.plot("Coregulation_MetaBrain")
curset <- datasets[["ALS_sumstats_EUR_ASIA_enrichtments_exHla_coregulation_only.xlsx"]]
p2 <- make.plot("Coregulation_MetaBrain")
curset <- datasets[["2020-04-28-ALS.replication_enrichtments_exHla_coregulation_only.xlsx"]]
p3 <- make.plot("Coregulation_MetaBrain")

grid.arrange(grobs=list(p1,p2,p3), ncol=3)
```


```{r}

bla <- read.depict2("~/Desktop/depict2/collaborations/harm_jan/2020-04-28-ALS.replication_enrichtments_exHla_coregulation_only.xlsx")
a  <- bla$Coregulation_MetaBrain
b  <- bla$Coregulation
ol <- intersect(rownames(a), rownames(b))

xy.plot.pvalue.colored(a[ol,]$Enrichment.Z.score, 
                       a[ol,]$Enrichment.P.value, 
                       b[ol,]$Enrichment.Z.score, 
                       b[ol,]$Enrichment.P.value,
                       xlab="MetaBrain",
                       ylab="GeneNetwork") +
  geom_hline(yintercept=0, lty=2, col="lightgrey") +
  geom_vline(xintercept=0, lty=2, col="lightgrey")
```

