```{r}
setwd("../downstreamer_collaborations/biogen/")
source("../../downstreamer_main/downstreamer_functions.r")

# Read excel files
base <- read.downstreamer.batch("/home/work/Desktop/depict2/collaborations/biogen/hand_grip_strength/2021-02-11/")
new <- read.downstreamer.batch("/home/work/Desktop/depict2/collaborations/biogen/hand_grip_strength/2021-03-09/")

  plot.auc.comparison <- function(auc.1, auc.pval.1, auc.2, auc.pval.2, xlab="AUC 1", ylab="AUC 2", main=NULL) {
  auc.pval.1[auc.1 == 0] <- 1
  auc.pval.2[auc.2 == 0] <- 1

  df.plot <- data.frame(auc.1=auc.1,
                        auc.2=auc.2,
                        signif.1 = auc.pval.1 < (0.05 / length(auc.1)), 
                        signif.2 = auc.pval.2 < (0.05 / length(auc.2)))
  
  
  df.plot$signif.both    <- (df.plot$signif.1 + df.plot$signif.2) == 2
  df.plot$signif.either  <- (df.plot$signif.1 + df.plot$signif.2) > 0
  df.plot <- df.plot[order(df.plot$signif.either),]

  lims <- c(min(c(auc.1, auc.2), na.rm=T), max(c(auc.1, auc.2), na.rm=T))  

  
  p <- ggplot(data=df.plot, mapping=aes(x=auc.1, y=auc.2)) +
    geom_point(alpha=0.75, mapping=aes(col=signif.either)) +
    geom_abline(slope=1, intercept=0, col="grey", lty=2) +
    coord_fixed() +
    xlab(xlab) +
    ylab(ylab) +
    ggtitle(main) + 
    scale_color_manual(values=c(`FALSE`="#2c6c70", `TRUE`="#0ae4f2")) +
    geom_smooth(method="lm") +
    xlim(lims) +
    ylim(lims)
  

  
  return(theme.nature(p))
}


```

# Hand grip strength
```{r}
#h.dom <- read.depict2("~/Desktop/depict2/collaborations/biogen/hand_grip_strength/2020-02-11/UKBB_hand_grip_strength_enrichtments_UKBB_dom_grip_abs_height_adj_1.xlsx")
#h.nondom <- read.depict2("~/Desktop/depict2/collaborations/biogen/hand_grip_strength/2020-02-11/UKBB_hand_grip_strength_enrichtments_UKBB_nondom_grip_abs_height_adj_1.xlsx")

# Dom vs nondom
plots <- list()

for  (database in names(h.dom)) {
  x <- h.dom[[database]]
  y <- h.nondom[[database]]
  
  ol <- intersect(rownames(x), rownames(y))
  
  p <- xy.plot.pvalue.colored(x[ol,]$Enrichment.Z.score,
                         x[ol,]$Enrichment.P.value,
                         y[ol,]$Enrichment.Z.score,
                         y[ol,]$Enrichment.P.value, 
                         pval.col="all",
                         xlab="Zscore dominant",
                         ylab="Zscore non-dominant",
                         main=database)
    
  plots[[database]] <- p
}

pdf(width=10, height=10, file="~/Desktop/depict2/collaborations/biogen/hand_grip_strength/2020-02-11/dominant_vs_nondominant_downstreamer_enrichment_results.pdf")
grid.arrange(grobs=plots, ncol=3)
dev.off()



plots <- list()

for (database in c("dom", "nondom")) {
  
  if (database=="dom") {
    #x <- h.dom[["GenePrioritization"]]
    #y <- h.dom[["GenePrioritization200"]]
    x <- base$UKBB_hand_grip_strength_UKBB_dom_grip_abs_height_adj_1$GenePrioritization200
    y <- new$UKBB_hand_grip_strength_UKBB_dom_grip_abs_height_adj_no_height_genes$GenePrioritization200
  } else {
    #x <- h.nondom[["GenePrioritization"]]
    #y <- h.nondom[["GenePrioritization200"]]
    x <- base$UKBB_hand_grip_strength_UKBB_nondom_grip_abs_height_adj_1$GenePrioritization200
    y <- new$UKBB_hand_grip_strength_UKBB_nondom_grip_abs_height_adj_no_height_genes$GenePrioritization200
  }

  
  ol <- intersect(rownames(x), rownames(y))
  
  p <- xy.plot.pvalue.colored(x[ol,]$Enrichment.Z.score,
                         x[ol,]$Enrichment.P.value,
                         y[ol,]$Enrichment.Z.score,
                         y[ol,]$Enrichment.P.value, 
                         pval.col="all",
                         xlab="Zscore with height genes",
                         ylab="Zscore wo height genes",
                         main=database)
    
  plots[[database]] <- p
}


pdf(width=10, height=5, file="~/Desktop/depict2/collaborations/biogen/hand_grip_strength/2021-03-09/results_with_height_genes_vs_without.pdf")
grid.arrange(grobs=plots, ncol=2)
dev.off()


```



# Metabrain
```{r}

make.plot <- function(trait) {

  curdata.x <- curset[[paste0(trait, "_MetaBrain")]]
  curdata.y <- curset[[paste0(trait, "_raw")]]
  ol        <- intersect(rownames(curdata.x), rownames(curdata.y))
  curdata.x <- curdata.x[ol,]
  curdata.y <- curdata.y[ol,]
  
  p <- plot.auc.comparison(curdata.x$Enrichment.Z.score, curdata.x$Enrichment.P.value, curdata.y$Enrichment.Z.score, curdata.y$Enrichment.P.value, xlab=paste0(trait, "_MetaBrain"), ylab=paste0(trait, "_raw"))
  
  return(p)
}


curset <- datasets[["2020-04-28-ALS.replication"]]

p1 <- make.plot("GO_F")
p2 <- make.plot("GO_C")
p3 <- make.plot("GO_P")
p4 <- make.plot("KEGG")
p5 <- make.plot("HPO")
p6 <- make.plot("Reactome")

grid.arrange(grobs=list(p1,p2,p3,p4,p5,p6), ncol=3)


curset <- datasets[["ALS_sumstats_EUR_ASIA"]]

p1 <- make.plot("GO_F")
p2 <- make.plot("GO_C")
p3 <- make.plot("GO_P")
p4 <- make.plot("KEGG")
p5 <- make.plot("HPO")
p6 <- make.plot("Reactome")

grid.arrange(grobs=list(p1,p2,p3,p4,p5,p6), ncol=3)




curset.x <- datasets[["2020-04-28-ALS.replication"]]
curset.y <- datasets[["ALS_sumstats_EUR_ASIA"]]

make.plot <- function(trait) {

  curdata.x <- curset.x[[paste0(trait, "_MetaBrain")]]
  curdata.y <- curset.y[[paste0(trait, "_MetaBrain")]]
  ol        <- intersect(rownames(curdata.x), rownames(curdata.y))
  curdata.x <- curdata.x[ol,]
  curdata.y <- curdata.y[ol,]
  
  p <- plot.auc.comparison(curdata.x$Enrichment.Z.score, curdata.x$Enrichment.P.value, curdata.y$Enrichment.Z.score, curdata.y$Enrichment.P.value, xlab=paste0(trait, "_exlAsia"), ylab=paste0(trait, "_inclAsia"))
  
  return(p)
}


p1 <- make.plot("GO_F")
p2 <- make.plot("GO_C")
p3 <- make.plot("GO_P")
p4 <- make.plot("KEGG")
p5 <- make.plot("HPO")
p6 <- make.plot("Reactome")

grid.arrange(grobs=list(p1,p2,p3,p4,p5,p6), ncol=3)


```

